baseline: Code ngôn ngữ nào cũng được, miễn lương thiện là được!
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: Tiếng nói của giai cấp Công nhân Lập trình
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Thợ Code
baseurl: /
canonicalurl: true
