baseline: Code gì cũng được, miễn có lương thiện là được!
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - ThoCode
  - Code Monkey
  - Software Engineer
  - Software Developer
  - Career path
  - Cloud
  - Web3
  - Blockchain
  - Metaverse
  - Cryptocurrency
author: ThoCode Team
description: Tiếng nói của giai cấp Công nhân Lập trình
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Thợ Code
baseurl: /
canonicalurl: true
